# 消費税設定ファイル
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: consumption_tax.yaml 1276 2009-06-15 14:16:44Z pooza $

rates:
  - rate: 0.05
    start_date: 1997-04-01
  - rate: 0.03
    start_date: 1989-04-01
