# ファイル関連設定ファイル
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: file.yaml 1671 2009-12-12 06:55:46Z pooza $

ignore_patterns:
  - \.DS_Store
  - \.svn
  - \.git
  - CVS
