# ファイル関連設定ファイル
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: file.yaml 1703 2009-12-21 10:12:38Z pooza $

ignore_patterns:
  - \.DS_Store
  - \.svn
  - \.git
  - CVS
