# メディアタイプ設定ファイル
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: mime.yaml 1862 2010-02-15 11:00:37Z pooza $

types:
  3gp: video/3gpp
  aac: audio/x-aac
  aif: audio/x-aiff
  aifc: audio/x-aiff
  aiff: audio/x-aiff
  as:
  css: text/css
  csv: text/csv
  dat: application/octet-stream
  doc: application/vnd.ms-word
  docx: application/vnd.openxmlformats-officedocument.wordprocessingml.document
  eml: message/rfc822
  eps: application/postscript
  flv: video/x-flv
  gif: image/gif
  gz: application/x-gzip
  h264: video/quicktime
  htm: text/html
  html: text/html
  ini: text/x-ini-file
  jpg: image/jpeg
  jpeg: image/jpeg
  js: text/javascript
  json: text/javascript
  m4p: audio/x-m4p
  mime: message/rfc822
  mov: video/quicktime
  mp3: audio/mpeg
  mp4: video/mp4
  mpeg: video/mpeg
  mpg: video/mpeg
  odp: application/vnd.oasis.opendocument.presentation
  ods: application/vnd.oasis.opendocument.spreadsheet
  odt: application/vnd.oasis.opendocument.text
  pdf: application/pdf
  php:
  pl:
  pm:
  png: image/png
  ppt: application/vnd.ms-powerpoint
  pptx: application/vnd.openxmlformats-officedocument.presentationml.presentation
  qt: video/quicktime
  rb:
  sql:
  swf: application/x-shockwave-flash
  tgz: application/x-gzip
  tif: image/tiff
  tiff: image/tiff
  tpl:
  ttf: application/x-truetype-font
  txt: text/plain
  wav: audio/x-wav
  wmv: video/x-ms-wmv
  wmv1: video/x-ms-wmv
  wmv2: video/x-ms-wmv
  wmv3: video/x-ms-wmv
  yaml: text/yaml
  yml: text/yaml
  xls: application/vnd.ms-excel
  xlsx: application/vnd.openxmlformats-officedocument.wordprocessingml.document
  xml: application/xml
  vcf: text/x-vcard
  zip: application/zip
