# 動画フォーマット設定ファイル
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: movie_format.yaml 1812 2010-02-03 15:15:09Z pooza $

types:
  flv: video/x-flv
  mov: video/quicktime
  h264: video/quicktime
  mpg: video/mpeg
  mpeg: video/mpeg
  mp4: video/mp4
  wmv1: video/x-ms-wmv
  wmv2: video/x-ms-wmv
  wmv3: video/x-ms-wmv
