# モジュール設定ファイル
#
# @package org.carrot-framework
# @subpackage UserPictogram
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: module.yaml 1093 2009-04-23 06:57:50Z pooza $

actions:
  Choice:
    title: 絵文字入力