# モジュール設定ファイル
#
# @package org.carrot-framework
# @subpackage UserPictogram
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: module.yaml 1812 2010-02-03 15:15:09Z pooza $

actions:
  Choice:
    title: 絵文字入力