# フィルタ設定ファイル
#
# @package org.carrot-framework
# @subpackage AdminUtility
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: filters.yaml 1791 2010-01-27 04:04:18Z pooza $

- class: BSSecurityFilter
- class: BSHostSecurityFilter
- class: BSMenuFilter
