# モジュール設定ファイル
#
# @package org.carrot-framework
# @subpackage AdminUtility
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: module.yaml 1819 2010-02-04 11:13:43Z pooza $

module:
  title: ユーティリティ

actions:
  Backup:
    title: バックアップ
  Pictogram:
    title: 絵文字入力