# フィルタ設定ファイル
#
# @package jp.co.commons.forms
# @subpackage AdminRegistration
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

- class: BSSecurityFilter
- class: BSHostSecurityFilter
- class: BSMenuFilter
