# バリデータ設定ファイル
#
# @package jp.co.b-shock.forms
# @author 小石達也 <tkoishi@b-shock.co.jp>

api_key:
  class: MincAPIValidator
field_type:
  class: BSRecordValidator
  params:
    class: FieldType
form:
  class: BSRecordValidator
  params:
    class: Form
