# バリデータ設定ファイル
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: carrot.yaml 1513 2009-09-20 13:27:06Z pooza $

date:
  class: BSDateValidator
email:
  class: BSMailAddressValidator
empty:
  class: BSEmptyValidator
english:
  class: BSEnglishValidator
file:
  class: BSFileValidator
  params:
    size: 2
    suffixes: attachable
flag:
  class: BSChoiceValidator
  params:
    choices:
      - 0
      - 1
flash:
  class: BSFlashValidator
html:
  class: BSHTMLFragmentValidator
  params:
    allowed_tags:
      - h1
      - h2
      - h3
      - h4
      - h5
      - h6
      - h7
      - p
      - br
      - table
      - tbody
      - th
      - tr
      - td
      - strike
      - strong
      - em
      - b
      - i
      - u
      - font
      - hr
      - a
      - ul
      - ol
      - li
      - img
image:
  class: BSImageValidator
  params:
    types:
      - image/gif
      - image/jpeg
      - image/png
kana:
  class: BSKanaValidator
longtext:
  class: BSStringValidator
  params:
    max: 65536
number:
  class: BSNumberValidator
password:
  class: BSPasswordValidator
pixel:
  class: BSNumberValidator
  params:
    min: 8
    max: 1024
string:
  class: BSStringValidator
  params:
    max: 1024
styleset:
  class: BSStyleSetValidator
tel:
  class: BSPhoneNumberValidator
tel_separated:
  class: BSPhoneNumberValidator
  params:
    fields:
      - tel1
      - tel2
      - tel3
tinytext:
  class: BSStringValidator
  params:
    max: 250
url:
  class: BSURLValidator
year:
  class: BSNumberValidator
  params:
    min: 1912
zipcode:
  class: BSZipcodeValidator
zipcode_separated:
  class: BSZipcodeValidator
  params:
    fields:
      - zipcode1
      - zipcode2

