# フィルタ設定ファイル
#
# @package org.carrot-framework
# @subpackage Console
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: filters.yaml 1533 2009-10-02 17:01:41Z pooza $

- class: BSConsoleSecurityFilter