# メニュー設定ファイル - 管理メニュー
#
# @package jp.co.commons.forms
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

- separator: yes
- module: AdminLog
- module: AdminMemcache
- module: DevelopTableReport
- title: APIドキュメント
  href: /man
  target: _blank
  credential: Develop
- title: アクセスログ解析
  href: /awstats/awstats.pl
  target: _blank
  credential: Admin
- separator: yes
- title: ログアウト
  module: Default
  action: Logout