# メニュー設定ファイル - 管理メニュー
#
# @package __PACKAGE__
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: admin.yaml 1278 2009-06-16 00:54:55Z pooza $

- separator: yes
- module: AdminLog
- module: AdminMemcache
- module: DevelopTableReport
- title: APIドキュメント
  href: /man
  target: _blank
  credential: Develop
- title: アクセスログ解析
  href: /awstats/awstats.pl
  target: _blank
  credential: Admin
- separator: yes
- title: ログアウト
  module: Default
  action: Logout