# メニュー設定ファイル - 管理メニュー
#
# @package jp.co.b-shock.forms
# @author 小石達也 <tkoishi@b-shock.co.jp>

- module: AdminForm
- separator: yes
- module: AdminLog
- module: DevelopTableReport
- separator: yes
- title: ログアウト
  module: Default
  action: Logout