# フィルタ設定ファイル
#
# @package jp.co.b-shock.forms
# @author 小石達也 <tkoishi@b-shock.co.jp>

- class: BSFakeUserAgentFilter
- class: BSLegacyUserAgentFilter
- class: BSEncodingRequestFilter
- class: BSNewLineRequestFilter
- class: BSCookieFilter
  params:
    excluded_actions:
      - Login
- class: BSKanaRequestFilter
  params:
    option: KVa
- class: BSReadingRequestFilter
- class: BSDateRequestFilter
- class: BSZipcodeRequestFilter
- class: BSWrongCharactersRequestFilter
