# フィルタ設定ファイル
#
# @package __PACKAGE__
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: application.yaml 1438 2009-09-06 11:15:30Z pooza $

- class: BSDeniedUserAgentFilter
- class: BSEncodingRequestFilter
- class: BSNewLineRequestFilter
- class: BSPictogramRequestFilter
- class: BSCookieFilter
- class: BSKanaRequestFilter
  params:
    option: KVa
- class: BSReadingRequestFilter
- class: BSDateRequestFilter
