# フィルタ設定ファイル
#
# @package jp.co.commons.forms
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

- class: BSDeniedUserAgentFilter
- class: BSPictogramRequestFilter
- class: BSEncodingRequestFilter
- class: BSNewLineRequestFilter
- class: BSCookieFilter
- class: BSKanaRequestFilter
  params:
    option: KVa
- class: BSReadingRequestFilter
- class: BSDateRequestFilter
- class: BSZipcodeRequestFilter
