# アプリケーション定数設定ファイル
#
# @package jp.co.commons.forms
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

app:
  name:
    ja: forms
    en: forms
  ver: 1.1.5(2010-10-17)

author:
  name: 有限会社 ビーショック
  email: info@b-shock.co.jp

crypt:
  salt: EGQ1TT4MXA
  engine: cbc

module:
  secure:
    module: Default
    action: Login

mail:
  include_answers: no

string:
  mobile:
    force_convert: yes