# アプリケーション定数設定ファイル
#
# @package jp.co.b-shock.forms
# @author 小石達也 <tkoishi@b-shock.co.jp>

app:
  name:
    ja: forms
    en: forms
  ver: 1.2.11 (2017-05-17)
author:
  name: 有限会社 ビーショック
  email: info@b-shock.co.jp
crypt:
  password: 35U68FVLNRSHLRYV
  digest:
    salt: 35U68FVLNRSHLRYV
module:
  secure:
    module: Default
    action: Login
mail:
  include_answers: no
serialize:
  storage: memcache
  classes:
    - Form
session:
  storage: memcache
