# アプリケーション定数設定ファイル
#
# @package jp.co.commons.forms
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

app:
  name:
    ja: forms
    en: forms
  ver: 1.0.0b5(2009-10-28)
  bts:
    url: http://redmine.carrot-framework.org/projects/show/forms
  svn:
    url: http://b-shock.co.jp/commons/forms/trunk

author:
  name: 有限会社 ビーショック
  email: info@b-shock.co.jp

crypt:
  salt: EGQ1TT4MXA
  engine: cbc

module:
  secure:
    module: Default
    action: Login
