# アプリケーション定数設定ファイル
#
# @package jp.co.commons.forms
# @author 小石達也 <tkoishi@b-shock.co.jp>

app:
  name:
    ja: forms
    en: forms
  ver: 1.2.0

author:
  name: 有限会社 ビーショック
  email: info@b-shock.co.jp

crypt:
  salt: EGQ1TT4MXA
  engine: cbc

module:
  prefixes:
    - Admin
    - Agent
    - User
    - Develop
    - Console
  secure:
    module: Default
    action: Login

mail:
  include_answers: no

string:
  mobile:
    force_convert: yes