# アプリケーション定数設定ファイル
#
# @package jp.co.commons.forms
# @author 小石達也 <tkoishi@b-shock.co.jp>

app:
  name:
    ja: 入力フォーム
    en: Registration Form
  ver: 1.0.0

author:
  name: 有限会社 ビーショック
  email: info@b-shock.co.jp

crypt:
  salt: EGQ1TT4MXA
  engine: cbc

module:
  secure:
    module: Default
    action: Login

mail:
  include_answers: no
