# アプリケーション定数設定ファイル
#
# @package jp.co.commons.forms
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

app:
  name:
    ja: __NAME_JA__
    en: __NAME_EN__
  ver: 1.0.0-dev
  bts:
    url: http://redmine.carrot-framework.org/projects/show/carrot
  svn:
    url: http://svn.carrot-framework.org/carrot/trunk

author:
  name: 有限会社 ビーショック
  email: info@b-shock.co.jp

crypt:
  salt: carrot
