# アプリケーション定数設定ファイル - carrot分
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: carrot.yaml 2118 2010-06-03 04:08:42Z pooza $

carrot:
  name: carrot Framework
  ver: 2.3.107

admin:
  email:
  password:
  jid:
  networks:
app:
  name:
    ja: unknown
    en: unknown
  ver: unknown
  xmpp:
    jid:
    password:
  basic_auth:
    uid:
    password:
  http_cache:
    mode: private
    seconds: 60
    send_expires: no
  force_https: no
author:
  name:
  email:
  password:
  twitter: carrot_fw
awstats:
  daily: yes
  server_name_aliases:
cookie:
  checker:
    hours: 6
crypt:
  salt: carrot
  engine: blowfish
  digest:
    method: sha1
date:
  timezone: Asia/Tokyo
debug: yes
ffmpeg:
  dir: /usr/local
file:
  types:
    file: /etc/httpd/mime.types
flash:
  player_ver: 9.0.0
  installer:
    href: /carrotlib/swf/expressInstall.swf
home:
  href: /index.html
image:
  mobile:
    size:
      width: 240
      height: 320
    type:
      docomo: image/jpeg
      au: image/png
      softbank: image/png
  qrcode:
    size: 2
    margin: 4
    type: image/png
  thumbnail:
    bgcolor: black
    type: image/png
languages:
  - ja
log:
  loggers:
    - file
    - mail
    - system
  syslog:
    facility: LOCAL6
  mail:
    patterns:
      - BSDatabaseException
      - BSFileException
  jabber:
    patterns:
      - BSDatabaseException
      - BSMailException
      - BSFileException
mail:
  sender: sendmail
memcache:
  daemon_name: memcached
  host: localhost
  port: 11211
module:
  prefixes:
    - Admin
    - User
    - Develop
  default:
    module: Default
    action: Default
  cookie_disabled:
    module: Default
    action: CookieDisabled
  not_found:
    module: Default
    action: NotFound
  secure:
    module: Default
    action: NotFound
  empty_site:
    module: Default
    action: EmptySite
movie:
  video_codec: flv
  audio_codec: libfaac
  flv:
    player:
      height: 0
      href: /carrotlib/swf/flowplayer-3.2.1.swf
      control_bar:
        href: /carrotlib/swf/flowplayer.controls-3.2.0.swf
  wmv:
    player:
      clsid: 6BF52A52-394A-11d3-B153-00C04F79FAA6
      height: 45
  quicktime:
    player:
      clsid: 02BF25D5-8C17-4B23-BC80-D3488ABDDC6B
      height: 16
music:
  mp3:
    player:
      href: /carrotlib/swf/player_mp3_maxi.swf
      width: 200
      height: 20
mysql:
  dir: /usr/local
net:
  resolvable: yes
  url:
    shorter: bitly
package:
  name:
  ver:
pdo:
  query_log:
    enable: no
  default:
    dsn: sqlite:%BS_VAR_DIR%/db/db.sqlite3
    loggable: yes
  geocode:
    dsn: sqlite:%BS_VAR_DIR%/db/geocode.sqlite3
  log:
    dsn: sqlite:%BS_VAR_DIR%/db/log.sqlite3
  serialize:
    dsn: sqlite:%BS_VAR_DIR%/db/serialize.sqlite3
  twitter:
    dsn: sqlite:%BS_VAR_DIR%/db/twitter.sqlite3
pictogram:
pgsql:
  dir: /usr/local
proctools:
  dir: /usr/local
request:
  validate:
    strict: no
sendmail:
  dir: /usr
serialize:
  storage: default
  serializer: JSON
  keep:
    - BSCounter.*
service:
  bitly:
    version: 2.0.1
    login: carrotfw
    api_key: R_dbbb70d7b5959e23289acfc3458f836f
  google:
    maps:
      api_key: ABQIAAAATsMwobOX_2h6mtmVGXYj7hRDPMaTZsAqlqCvYqUSXVpA0IN8hBR3QFfr0mhWyh4H99uEfkf2XzBZyA
      zoom: 17
      format: gif
    analytics:
      id:
      beacon_href: /carrotlib/php/ga.php
  twitter:
    consumer:
      key: hhXdKP3kEwvWumb1AFbTlQ
      secret: m5dkKU4xnuLfD5WHOpctisvR08rSfB80x9Bfy0nnlk
    suffix: .json
    minutes: 5
session:
  storage: default
  regenerate_id: no
smtp:
  host: localhost
  check_addresses: no
sqlite3:
  dir: /usr/local
string:
  mobile:
    force_convert: no
upload:
  progress:
    key: progress_key
xmpp:
  host: talk.google.com
  port: 5222
  server: gmail.com
  ssl: yes
