# ホスト別設定ファイル
#
# @package jp.co.commons.forms
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id$

root_url: http://carrot.gisarme.local/
root_url_https: http://carrot.gisarme.local/
debug: yes

admin:
  email: admin@b-shock.co.jp
  password: 7e240de74fb1ed08fa08d38063f6a6a91462a815
  jid: tatsuya.koishi@gmail.com
  networks:
    - 192.168.102.0/24

types:
  #file: %BS_WEBAPP_DIR%/config/mime/mime.types

pdo:
  default:
    #dsn: mysql:host=127.0.0.1;dbname=carrot
    #dsn: pgsql:host=localhost dbname=carrot user=postgres
    uid: root
    password:

smtp:
  host: localhost

awstats:
  log_dir: /var/log/httpd/www.example.com
  server_name_aliases: 
