# アプリケーション定数設定ファイル - carrot分
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: carrot.yaml 1736 2010-01-02 09:04:41Z pooza $

carrot:
  name: carrot Framework
  ver: 2.3.32
  bts:
    url: http://redmine.carrot-framework.org/projects/show/carrot

admin:
  email:
  password:
  jid:
  networks:
app:
  name:
    ja: unknown
    en: unknown
  ver: unknown
  bts:
    url: http://redmine.carrot-framework.org/projects/show/carrot
  xmpp:
    jid:
    password:
author:
  name:
  email:
  password:
awstats:
  daily: yes
  server_name_aliases:
crypt:
  salt: carrot
  engine: blowfish
date:
  timezone: Asia/Tokyo
debug: yes
feed:
  class: BSRSS20Document
ffmpeg:
  dir: /usr/local
flash:
  href_prefix: /carrotlib/swf/
  player_ver: 8.0.0
  installer:
    href: /carrotlib/swf/expressInstall.swf
home:
  href: /index.html
image:
  mobile:
    type:
      docomo: image/jpeg
      au: image/png
      softbank: image/png
  qrcode:
    size: 2
    margin: 4
    type: image/png
  thumbnail:
    bgcolor: black
    type: image/png
languages:
  - ja
log:
  loggers:
    - file
    - mail
    - system
  syslog:
    facility: LOCAL6
  mail:
    patterns:
      - BSDatabaseException
      - BSFileException
  jabber:
    patterns:
      - BSDatabaseException
      - BSMailException
      - BSFileException
memcache:
  daemon_name: memcached
  host: localhost
  port: 11211
module:
  prefixes:
    - Admin
    - User
    - Develop
  default:
    module: Default
    action: Default
  not_found:
    module: Default
    action: NotFound
  secure:
    module: Default
    action: NotFound
movie:
  href_prefix: /carrotlib/movies/
  video_codec: flv
  audio_codec: libfaac
  flv:
    player:
      height: 24
      href: /carrotlib/swf/flowplayer-3.1.4.swf
  wmv:
    player:
      clsid: 6BF52A52-394A-11d3-B153-00C04F79FAA6
      height: 45
  quicktime:
    player:
      clsid: 02BF25D5-8C17-4B23-BC80-D3488ABDDC6B
      height: 16
mysql:
  dir: /usr/local
net:
  resolvable: yes
  url:
    shorter: bitly
package:
  name:
  ver:
pdo:
  query_log:
    enable: no
  default:
    dsn: sqlite:%BS_VAR_DIR%/db/db.sqlite3
    loggable: yes
  log:
    dsn: sqlite:%BS_VAR_DIR%/db/log.sqlite3
  session:
    dsn: sqlite:%BS_VAR_DIR%/db/session.sqlite3
  serialize:
    dsn: sqlite:%BS_VAR_DIR%/db/serialize.sqlite3
pictogram:
pgsql:
  dir: /usr/local
proctools:
  dir: /usr/local
request:
  validate:
    strict: no
serialize:
  storage: default
  serializer: JSON
  keep:
    - BSCounter.*
service:
  bitly:
    version: 2.0.1
    login: carrotfw
    api_key: R_dbbb70d7b5959e23289acfc3458f836f
session:
  storage: default
  regenerate_id: no
smarty:
  cache:
    storage: default
    life_time: 300
smtp:
  host: localhost
  check_addresses: no
sqlite3:
  dir: /usr/local
string:
  mobile:
    force_convert: no
types:
  file: /etc/httpd/mime.types
xmpp:
  host: talk.google.com
  port: 5222
  server: gmail.com
  ssl: yes
