# ホスト別設定ファイル
#
# @package jp.co.commons.forms
# @author 小石達也 <tkoishi@b-shock.co.jp>

root_url: http://forms.toroid.local/
root_url_https: http://forms.toroid.local/
debug: yes

root_site:
  root_url:

admin:
  email: admin@b-shock.co.jp
  password: 7e240de74fb1ed08fa08d38063f6a6a91462a815
  networks:
    - 192.168.102.0/24

author:
  email: info@b-shock.co.jp
  password: 7e240de74fb1ed08fa08d38063f6a6a91462a815

app:
  process:
    uid: www

pdo:
  default:
    dsn: mysql:host=127.0.0.1;dbname=forms
    uid: root
    password:
