root_url: http://forms.kapi.local/
root_url_https: http://forms.kapi.local/
debug: yes

root_site:
  root_url:
admin:
  email: admin@b-shock.co.jp
  password: $2y$10$LjpJMX8FeDuKo64cxADOcu6QRUMRoM/POOkUVvJvwpeMLF0OBdae2
author:
  email: info@b-shock.co.jp
  password: $2y$10$lKwMKi0eEcBBv9.AfOAesOIA1vw/3bPTTMY3ygve4J3BI/H7VvQt2
crypt:
  salt: FSKJB7LYUW
pdo:
  default:
    dsn: mysql:host=127.0.0.1;dbname=forms;charset=utf8mb4
    uid: root
    password: xsxYPqgVRieRWPmW36IFAGV0QVEO6s/qA1ZZX+cAqxVUdUxhtMRnmzqLF1XjzcOD
