# ホスト別設定ファイル
#
# @package jp.co.commons.forms
# @author 小石達也 <tkoishi@b-shock.co.jp>

root_url: http://test.forms.uenogakuen.ed.jp/
root_url_https: http://test.forms.uenogakuen.ed.jp/
debug: yes

admin:
  email: admin@uenogakuen.ed.jp
  password: b53d37f00808f03ac23cf2593f13ab358c5e52b9

author:
  name: 上野学園 中学校・高等学校
  email: info@uenogakuen.ed.jp
  password: d24230852721c8130849d189a07a56919b874f60

pdo:
  default:
    dsn: mysql:host=localhost;dbname=forms_test
    uid: httpd
    password: 4x69ITuoRCJL6u1l2zc1sA==

smtp:
  host: mail.uenogakuen.ed.jp

crypt:
  engine: blowfish
