# ディレクトリレイアウト設定ファイル
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: carrot.yaml 2212 2010-07-10 12:53:44Z pooza $

awstats:
  parent: lib
  name: AWStats
awstats_data:
  parent: var
awstats_log:
  constant: yes
backup:
  parent: var
  suffix: .zip
  purge:
    month: 1
bin:
  constant: yes
cache:
  parent: var
  suffix: .cache.php
carrot:
  parent: lib
carrotlib:
  parent: www
config:
  parent: webapp
compile:
  parent: var
css:
  parent: carrotlib
  suffix: .css
css_cache:
  parent: var
  suffix: .css
  href: /carrotlib/css/cache/
db:
  parent: var
  suffix: .sqlite3
dictionaries:
  parent: webapp
  class: BSDictionaryDirectory
dump:
  parent: var
  suffix: .sql
  purge:
    month: 1
favicon:
  parent: var
  suffix: .png
  href: /carrotlib/images/favicon/
  purge:
    day: 7
ffmpeg:
  constant: yes
font:
  parent: share
  suffix: .ttf
images:
  parent: carrotlib
image_cache:
  parent: var
  href: /carrotlib/images/cache/
  purge:
    day: 7
js:
  parent: carrotlib
  suffix: .js
js_cache:
  parent: var
  suffix: .js
  href: /carrotlib/js/cache/
lib:
  constant: yes
local_lib:
  parent: webapp
  name: lib
log:
  parent: var
  class: BSLogDirectory
  purge:
    month: 3
man:
  parent: share
maps:
  parent: var
  suffix: .gif
  href: /carrotlib/images/maps/
  purge:
    month: 1
menu:
  parent: config
modules:
  parent: webapp
movies:
  parent: carrotlib
  suffix: .flv
musics:
  parent: carrotlib
  suffix: .mp3
mysql:
  constant: yes
pictogram:
  parent: images
png2ico:
  constant: yes
proctools:
  constant: yes
pgsql:
  constant: yes
request:
  parent: var
  suffix: .txt
  purge:
    day: 7
root:
  constant: yes
sendmail:
  constant: yes
serialized:
  parent: var
share:
  constant: yes
sql:
  parent: share
  suffix: .sql
sqlite3:
  constant: yes
swf:
  parent: carrotlib
  suffix: .swf
templates:
  parent: webapp
  suffix: .tpl
tmp:
  parent: var
  purge:
    day: 7
twitter_account:
  parent: var
  suffix: .png
  purge:
    day: 1
var:
  constant: yes
webapp:
  constant: yes
www:
  constant: yes
