# JavaScriptセット設定ファイル
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: carrot.yaml 2135 2010-06-12 08:39:20Z pooza $

carrot:
  files:
    - prototype
    - scriptaculous/effects
    - scriptaculous/builder
    - ajaxzip3
    - lightbox
    - prototabs
    - protocalendar/protocalendar
    - protocalendar/lang_ja
    - usermenu
    - elevator
    - jsProgressBarHandler
    - flowplayer-3.2.0
    - carrot
    - application
