# JavaScriptセット設定ファイル
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: carrot.yaml 1558 2009-10-16 03:25:12Z pooza $

carrot:
  files:
    - prototype
    - scriptaculous/effects
    - ajaxzip2/ajaxzip2
    - prototabs
    - protocalendar/protocalendar
    - protocalendar/lang_ja
    - usermenu
    - elevator
    - flowplayer-3.1.4.min
    - carrot
    - application
