# JavaScriptセット設定ファイル
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: carrot.yaml 1994 2010-04-11 08:49:02Z pooza $

carrot:
  files:
    - prototype
    - scriptaculous/effects
    - scriptaculous/builder
    - ajaxzip2/ajaxzip2
    - lightbox
    - prototabs
    - protocalendar/protocalendar
    - protocalendar/lang_ja
    - usermenu
    - elevator
    - jsProgressBarHandler
    - flowplayer-3.1.4.min
    - carrot
    - application
