# JavaScriptセット設定ファイル
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: carrot.yaml 1315 2009-07-09 17:32:31Z pooza $

carrot:
  files:
    - prototype
    - scriptaculous/effects
    - ajaxzip2/ajaxzip2
    - prototabs
    - protocalendar/protocalendar
    - protocalendar/lang_ja
    - usermenu
    - elevator
    - carrot
    - application
