# モジュール設定ファイル
#
# @package org.carrot-framework
# @subpackage AdminLog
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: module.yaml 1812 2010-02-03 15:15:09Z pooza $

module:
  title_menu: 管理ログ
  title: 管理ログ閲覧モジュール

actions:
  Browse:
    title: 管理ログ
  Feed:
    filters:
      - class: BSSecurityFilter
        enabled: no
      - class: BSBasicAuthFilter
        enabled: yes
      - class: BSMenuFilter
        enabled: no
