# フィルタ設定ファイル
#
# @package org.carrot-framework
# @subpackage AdminMemcache
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: filters.yaml 975 2009-03-12 10:00:50Z pooza $

- class: BSSecurityFilter
- class: BSHostSecurityFilter
- class: BSMenuFilter
