# モジュール設定ファイル
#
# @package org.carrot-framework
# @subpackage AdminMemcache
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: module.yaml 1812 2010-02-03 15:15:09Z pooza $

module:
  title_menu: Memcache
  title: Memcache管理モジュール

actions:
  Summary:
    title: Memcacheの状態
