# フィルタ設定ファイル
#
# @package org.carrot-framework
# @subpackage DevelopTableReport
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: filters.yaml 1812 2010-02-03 15:15:09Z pooza $

- class: BSSecurityFilter
- class: BSHostSecurityFilter
- class: BSMenuFilter
  params:
    name: admin
