# モジュール設定ファイル
#
# @package org.carrot-framework
# @subpackage DevelopTableReport
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: module.yaml 980 2009-03-15 09:16:40Z pooza $

module:
  title_menu: TableReport
  title: TableReportモジュール

actions:
  DatabaseList:
    title: データベース一覧