# スタイルセット設定ファイル
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: carrot.yaml 1179 2009-05-12 06:59:13Z pooza $

carrot:
  files:
    - carrot
    - protocalendar
    - prototabs
    - application

carrot.Detail:
  files:
    - carrot
    - carrot.Detail
    - protocalendar
    - prototabs
    - application

carrot.LoginForm:
  files:
    - carrot
    - carrot.LoginForm
    - application
