# スタイルセット設定ファイル
#
# @package org.carrot-framework
# @author 小石達也 <tkoishi@b-shock.co.jp>
# @version $Id: carrot.yaml 1812 2010-02-03 15:15:09Z pooza $

carrot:
  files:
    - carrot
    - protocalendar
    - prototabs
    - application

carrot.Detail:
  files:
    - carrot
    - carrot.Detail
    - protocalendar
    - prototabs
    - lightbox
    - application

carrot.LoginForm:
  files:
    - carrot
    - carrot.LoginForm
    - application
